### ISSUE TITLE
URL patterns should be cleaned up

### ISSUE THREAD

**Issue by theadamparker** [rehman553/Racism#13]
Rather than linking directly to a file called `fr.html` we should use a pattern that doesn't should the `.html` file extension. So only `/fr/` is appended to the URL. 

French abbreviation is `fr`.
Spanish abbreviation is `es`.

**Comment by rehman553** [comment]
We have 3 html pages .html will needed to open them up

**Comment by theadamparker** [comment]
@rehman553 I would suggest the following structure. English is the default language and should be the `index.html` file in the root directory. You can create a new directories for Spanish and for French and put each HTML file within its respective directory named `index.html`. Note, the Spanish and French HTML files may need changes to relative file paths for CSS, JS, images, etc.
```
├── racism
└── index.html
│   ├── es
│   │   ├── index.html
│   ├── fr
│   │   ├── index.html
│   ├── css
│   ├── media
│   ├── fonts
│   ├── images
│   ├── js
```

**Comment by theadamparker** [comment]
Validated
