### ISSUE TITLE
Social icon links need URLs

### ISSUE THREAD

**Issue by theadamparker** [rehman553/Racism#6]
Please use the following URLs for social icons:

### English

- [Facebook](https://www.facebook.com/UNDP)
- [Twitter](https://twitter.com/UNDP/)
- [Instagram](https://www.instagram.com/UNDP/)
- [Linkedin](https://www.linkedin.com/company/undp/)
- [Youtube](https://www.youtube.com/UNDP/)

### Spanish (different from English)

- [Facebook](https://www.facebook.com/PNUD/) _*this is different_
- [Twitter](https://twitter.com/pnud) _*this is different_
- [Instagram](https://www.instagram.com/UNDP/)
- [Linkedin](https://www.linkedin.com/company/undp/)
- [Youtube](https://www.youtube.com/UNDP/)

### French (same as English)

- [Facebook](https://www.facebook.com/UNDP)
- [Twitter](https://twitter.com/UNDP/)
- [Instagram](https://www.instagram.com/UNDP/)
- [Linkedin](https://www.linkedin.com/company/undp/)
- [Youtube](https://www.youtube.com/UNDP/)

**Comment by rehman553** [comment]
English version links added

**Comment by mrelevo** [comment]
thanks Rehman, I dont see the FR/SP sites published yet, so cannot verify if the SM links are correct there

**Comment by mrelevo** [comment]
verfiied
