### ISSUE TITLE
Language selector

### ISSUE THREAD

**Issue by mrelevo** [rehman553/Racism#8]
While we wait to receive the FR/SP translations, please implement the Language selector using dummy target links to see the behavior of the language selector as user clicks to select a language. Behavior and treatment should be like this https://strategicplan.undp.org/ minus the pdf links

**Comment by rehman553** [comment]
I use this language drop from the design system, I use both the css and js files but still it is not working i want to confirm is there any specific jQuery library that I have to use? 

The js I use from design system 
https://undp.github.io/design-system/js/lang-switcher.min.js

The css I use from the design system 
https://undp.github.io/design-system/css/components/language-switcher.min.css

**Comment by theadamparker** [comment]
@rehman553 the `defer` attribute used to load the jQuery library caused issues for me. Also you will need to initialize the function by calling it like this

```
$(document).ready(function () {
    langSwitch()
}); 
```
With those changes it works for me. 

https://user-images.githubusercontent.com/2205158/161804228-2504269b-1bb5-4ac7-acd8-d6ef7feccd46.mov

**Comment by mrelevo** [comment]
looks good thanks
